let user=null, cfg=null, stream=null;
const $=id=>document.getElementById(id);
const deviceId=localStorage.deviceId || (localStorage.deviceId='dev_'+Math.random().toString(16).slice(2)+Date.now());
async function api(path,opt={}){ const res=await fetch(path,{headers:{'Content-Type':'application/json'},...opt}); const data=await res.json().catch(()=>({ok:false,message:'Respon server tidak valid'})); if(!res.ok) throw new Error(data.message||'Request gagal'); return data; }
async function status(){ try{ const d=await api('/api/status'); cfg=d.config; $('serverPill').textContent='Server Online'; $('serverPill').className='pill on'; $('serverTime').textContent=d.status.serverTime; $('radius').textContent=d.config.store.radiusMeter+' m'; }catch(e){ $('serverPill').textContent='Server Offline'; $('serverPill').className='pill'; } }
setInterval(status,5000); status();
function show(id){ ['loginView','employeeView','ownerView'].forEach(x=>$(x).classList.add('hidden')); $(id).classList.remove('hidden'); }
async function login(){ $('loginMsg').textContent='Memeriksa akun...'; try{ const d=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('username').value.trim(),password:$('password').value,deviceId,deviceName:navigator.userAgent.slice(0,80)})}); user=d.user; localStorage.user=JSON.stringify(user); $('loginMsg').textContent=''; if(user.role==='Owner') {show('ownerView'); loadOwner();} else {show('employeeView'); startCamera();} }catch(e){ $('loginMsg').textContent=e.message; $('loginMsg').className='msg bad'; } }
function logout(){ user=null; localStorage.removeItem('user'); if(stream) stream.getTracks().forEach(t=>t.stop()); show('loginView'); }
async function startCamera(){ try{ stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false}); $('video').srcObject=stream; }catch(e){ $('empMsg').textContent='Kamera belum diizinkan. Selfie tetap wajib di HP.'; } }
function getPos(){ return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})); }
function selfie(){ const v=$('video'), c=$('canvas'); if(!v.videoWidth) return ''; c.width=v.videoWidth; c.height=v.videoHeight; c.getContext('2d').drawImage(v,0,0); return c.toDataURL('image/jpeg',.55); }
async function checkin(){ $('empMsg').textContent='Mengambil GPS dan jam server...'; try{ const pos=await getPos(); const d=await api('/api/attendance/checkin',{method:'POST',body:JSON.stringify({userId:user.id,name:user.name,lat:pos.lat,lng:pos.lng,selfie:selfie()})}); const a=d.attendance; $('empMsg').className='msg ok'; $('empMsg').textContent=`${a.status} • ${a.serverTime} • ${a.distanceMeter} m • ${a.note}`; }catch(e){ $('empMsg').className='msg bad'; $('empMsg').textContent=e.message; } }
async function sendPermission(){ const reason=prompt('Alasan izin/sakit:')||'-'; try{ await api('/api/attendance/permission',{method:'POST',body:JSON.stringify({userId:user.id,name:user.name,type:'IZIN',reason})}); $('empMsg').className='msg ok'; $('empMsg').textContent='Izin terkirim ke owner.'; }catch(e){ $('empMsg').className='msg bad'; $('empMsg').textContent=e.message; } }
async function loadOwner(){ try{ const d=await api('/api/owner/dashboard'); const s=d.summary; $('summary').innerHTML=[['Hadir',s.hadir],['Telat',s.telat],['Izin',s.izin],['Ditolak',s.ditolak]].map(x=>`<div class="mini"><small>${x[0]}</small><b>${x[1]}</b></div>`).join(''); $('devices').innerHTML=(d.devices.length?d.devices:[{name:'Belum ada perangkat',role:'-',lastSeen:'-'}]).map(x=>`<div class="item"><div><b>${x.name}</b><br><small>${x.role} • ${new Date(x.lastSeen).toLocaleString('id-ID')}</small></div><span class="tag VALID">ONLINE</span></div>`).join(''); $('recent').innerHTML=(d.recent.length?d.recent:[{name:'Belum ada absen',serverTime:'-',distanceMeter:'-',status:'VALID',note:'-'}]).map(x=>`<div class="item"><div><b>${x.name}</b><br><small>${x.serverTime} • ${x.distanceMeter} m • ${x.note||''}</small></div><span class="tag ${x.status}">${x.status}</span></div>`).join(''); }catch(e){ $('ownerMsg').textContent=e.message; } }
setInterval(()=>{ if(user && user.role==='Owner') loadOwner(); if(user) api('/api/device/ping',{method:'POST',body:JSON.stringify({userId:user.id,name:user.name,role:user.role,deviceId,deviceName:navigator.userAgent.slice(0,80)})}).catch(()=>{}); },8000);
async function addEmployee(){ try{ await api('/api/owner/employee',{method:'POST',body:JSON.stringify({name:$('empName').value,username:$('empUser').value,password:$('empPass').value,role:$('empRole').value||'Karyawan'})}); $('ownerMsg').className='msg ok'; $('ownerMsg').textContent='Karyawan ditambahkan.'; loadOwner(); }catch(e){ $('ownerMsg').className='msg bad'; $('ownerMsg').textContent=e.message; } }
try{ user=JSON.parse(localStorage.user||'null'); if(user){ if(user.role==='Owner'){show('ownerView');loadOwner();} else {show('employeeView');startCamera();} } }catch(e){}
